modLoader="javafml"

loaderVersion="[1,)"

license="GNU GPLv3"

[[mods]]
modId="sablespawner"

version="1.0.0"

displayName="Sable Spawner"

description='''
刷怪，刷子维度，还有可配置的数据包
'''

[[dependencies.sablespawner]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.231,)"
    ordering="NONE"
    side="BOTH"


[[dependencies.sablespawner]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.sablespawner]]
    modId="sable"
    type="required"
    versionRange="[2.0.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.sablespawner]]
    modId="sable_schematic_api"
    type="required"
    versionRange="[0.4.0,)"
    ordering="AFTER"
    side="BOTH"

